version: '3.8'

services:
  frontend-dev:
    build:
      context: .                    
      dockerfile: Dockerfile  
    
    ports:
      - "4200:4200"              
    
    volumes:
      - .:/app                    
      - /app/node_modules          
    
    environment:
      - NODE_ENV=development       
      - CHOKIDAR_USEPOLLING=true   
    
    stdin_open: true             
    tty: true                     
    
    networks:
      - expense-network           
  
networks:
  expense-network:
    driver: bridge